%Take the generated artificial problems and calculate samples that will be used to calculate the landscape features
load('combined_set.mat'); 
%combined_set contains the variables:
%Functions, which is a cell array of functions generated by the artificial problem generator
%Best, wich is a cell array of the best performing algorithm for each function
%These can be generated using the function generate.m available at  https://github.com/BIMK/Algorithm-Recommendation


for sample_size = 250
    nfun = 10000;
    for iter = 1:10
        D = 10;
        samples = lhsdesign(sample_size * D, D);

        sample_range = 10;
        samples = samples*sample_range-sample_range/2;

        %samples matrix rows to cell array
        samples_cell = num2cell(samples,2);

        %for i = 1:length(Functions)
        for i = all_indexes
            f = Functions{i};
            disp(f);
            y = cellfun(f, samples_cell);
            combined_data = [samples, y];
            filename = strcat(num2str(iter), "_",  num2str(i), "_samples_", Best{i}, "_", num2str(sample_size), "_");
            filename = strcat("E:/ML_Samples_new_2/", filename);
            disp(filename);
            save(filename, 'combined_data')
        end
    end
    %save Best Best
end